/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FIFO.java
 *
 * Created on May 3, 2011, 5:42:14 PM
 */
package EscalonamentoProcessos;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Flavio Ricardo
 */
public class FIFO extends javax.swing.JFrame {

    public JTextField[] ProcessId;
    public JTextField[] Burst;
    public JTextField[] Arrival;
    public JTextField[] Priority;

    /** Creates new form FIFO */
    public FIFO() {
        initComponents();
        setLocationRelativeTo(null);
        fazAlgumaCoisa();
    }

//    FIFO(JTextField[] ProcessId, JTextField[] Burst, JTextField[] Arrival, JTextField[] Priority) {
//        this.ProcessId = ProcessId;
//        this.Burst = Burst;
//        this.Arrival = Arrival;
//        this.Priority = Priority;
//    }

    public final void fazAlgumaCoisa() {
//        for (int i = 0; i < this.ProcessId.length; i++) {
            JOptionPane.showMessageDialog(null, "Show me the code!");
//        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FIFOPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("The Scheduler » FIFO");
        setMinimumSize(new java.awt.Dimension(705, 515));
        setName("FIFO"); // NOI18N

        FIFOPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout FIFOPanelLayout = new javax.swing.GroupLayout(FIFOPanel);
        FIFOPanel.setLayout(FIFOPanelLayout);
        FIFOPanelLayout.setHorizontalGroup(
            FIFOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );
        FIFOPanelLayout.setVerticalGroup(
            FIFOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FIFOPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FIFOPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FIFO().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FIFOPanel;
    // End of variables declaration//GEN-END:variables
}