/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home.java
 *
 * Created on Apr 25, 2011, 6:43:32 PM
 */
package EscalonamentoProcessos;

/**
 *
 * @author flavio
 */
public class Home extends javax.swing.JFrame {

    /** Creates new form Home */
    public Home() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ProcessMenu = new javax.swing.JMenu();
        ProcessMenuItem = new javax.swing.JMenuItem();
        InformationMenu = new javax.swing.JMenu();
        HelpMenuItem = new javax.swing.JMenuItem();
        AboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCSA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("Home"); // NOI18N
        setResizable(false);

        HomePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        ProcessMenu.setText("Process");

        ProcessMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        ProcessMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Images/application_new.png"))); // NOI18N
        ProcessMenuItem.setText("New");
        ProcessMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProcessMenuItemMousePressed(evt);
            }
        });
        ProcessMenu.add(ProcessMenuItem);

        jMenuBar1.add(ProcessMenu);

        InformationMenu.setText("Information");

        HelpMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        HelpMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Images/help.png"))); // NOI18N
        HelpMenuItem.setText("Help");
        HelpMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HelpMenuItemMousePressed(evt);
            }
        });
        InformationMenu.add(HelpMenuItem);

        AboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        AboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Images/information.png"))); // NOI18N
        AboutMenuItem.setText("About");
        AboutMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AboutMenuItemMousePressed(evt);
            }
        });
        InformationMenu.add(AboutMenuItem);

        jMenuBar1.add(InformationMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProcessMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProcessMenuItemMousePressed
        new Process().setVisible(true);
    }//GEN-LAST:event_ProcessMenuItemMousePressed

    private void HelpMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMenuItemMousePressed
        new Help().setVisible(true);
    }//GEN-LAST:event_HelpMenuItemMousePressed

    private void AboutMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMenuItemMousePressed
        new About().setVisible(true);
}//GEN-LAST:event_AboutMenuItemMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenuItem;
    private javax.swing.JMenuItem HelpMenuItem;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JMenu InformationMenu;
    private javax.swing.JMenu ProcessMenu;
    private javax.swing.JMenuItem ProcessMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
