/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Process.java
 *
 * Created on Apr 25, 2011, 6:47:59 PM
 */
package EscalonamentoProcessos;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author flavio
 */
public class Process extends javax.swing.JFrame {

    /** Creates new form Process */
    public Process() {
        initComponents();
    }

    public void clearProcessPanel(int i, int beforeAmount, int presentAmount) {
        if (presentAmount < beforeAmount) {
            ProcessPanel.remove(i);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProcessPanel = new javax.swing.JPanel();
        AmountLabel = new javax.swing.JLabel();
        AmountComboBox = new javax.swing.JComboBox();
        ProcessIdLabel = new javax.swing.JLabel();
        CPUBurstLabel = new javax.swing.JLabel();
        ArrivalLabel = new javax.swing.JLabel();
        PriorityLabel = new javax.swing.JLabel();
        AlgorithmLabel = new javax.swing.JLabel();
        AlgorithmComboBox = new javax.swing.JComboBox();
        AlgorithmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCSA - Proccess");
        setName("ProcessFrame"); // NOI18N
        setResizable(false);

        ProcessPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AmountLabel.setText("Amount of Process");

        AmountComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select an Option", "1", "2", "3", "4", "5", "10" }));
        AmountComboBox.setToolTipText("Select the number of processes");
        AmountComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountComboBoxActionPerformed(evt);
            }
        });

        ProcessIdLabel.setText("Process ID");

        CPUBurstLabel.setText("CPU burst");

        ArrivalLabel.setText("Arrival");

        PriorityLabel.setText("Priority");

        AlgorithmLabel.setText("Select an Algorithm");

        AlgorithmComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select an Option", "FCFS", "SJF preemptivo (SRT)", "SJF não preemptivo", "Round Robin", "Loteria" }));

        AlgorithmButton.setText("Go");
        AlgorithmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgorithmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProcessPanelLayout = new javax.swing.GroupLayout(ProcessPanel);
        ProcessPanel.setLayout(ProcessPanelLayout);
        ProcessPanelLayout.setHorizontalGroup(
            ProcessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProcessPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProcessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProcessPanelLayout.createSequentialGroup()
                        .addComponent(AmountLabel)
                        .addGap(18, 18, 18)
                        .addComponent(AmountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AlgorithmLabel)
                        .addGap(18, 18, 18)
                        .addComponent(AlgorithmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(AlgorithmButton))
                    .addGroup(ProcessPanelLayout.createSequentialGroup()
                        .addComponent(ProcessIdLabel)
                        .addGap(42, 42, 42)
                        .addComponent(CPUBurstLabel)
                        .addGap(45, 45, 45)
                        .addComponent(ArrivalLabel)
                        .addGap(62, 62, 62)
                        .addComponent(PriorityLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProcessPanelLayout.setVerticalGroup(
            ProcessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProcessPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProcessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountLabel)
                    .addComponent(AmountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlgorithmLabel)
                    .addComponent(AlgorithmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlgorithmButton))
                .addGap(18, 18, 18)
                .addGroup(ProcessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProcessIdLabel)
                    .addGroup(ProcessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ArrivalLabel)
                        .addComponent(PriorityLabel))
                    .addComponent(CPUBurstLabel))
                .addContainerGap(358, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProcessPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProcessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AmountComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountComboBoxActionPerformed
        int amount = Integer.parseInt(AmountComboBox.getSelectedItem().toString());
        if (amount != 0) {
            if (JOptionPane.showConfirmDialog(null, "Register " + amount + " processes?") == 0) {
                JTextField[] ProcessIdTextFields = new JTextField[amount];
                JTextField[] BurstTextFields = new JTextField[amount];
                JTextField[] ArrivalTextFields = new JTextField[amount];
                JTextField[] PriorityTextFields = new JTextField[amount];
                for (int i = 0; i < amount; i++) {
                    ProcessIdTextFields[i] = new JTextField();
                    ProcessIdTextFields[i].setBounds(14, (i == 0) ? 85 : 80 + (35 * i), 75, 25);
                    ProcessIdTextFields[i].setText(null);
                    ProcessIdTextFields[i].setVisible(true);
                    ProcessPanel.add(ProcessIdTextFields[i]);

                    BurstTextFields[i] = new JTextField();
                    BurstTextFields[i].setBounds(117, (i == 0) ? 85 : 80 + (35 * i), 75, 25);
                    BurstTextFields[i].setText(null);
                    BurstTextFields[i].setVisible(true);
                    ProcessPanel.add(BurstTextFields[i]);

                    ArrivalTextFields[i] = new JTextField();
                    ArrivalTextFields[i].setBounds(220, (i == 0) ? 85 : 80 + (35 * i), 75, 25);
                    ArrivalTextFields[i].setText(null);
                    ArrivalTextFields[i].setVisible(true);
                    ProcessPanel.add(ArrivalTextFields[i]);

                    PriorityTextFields[i] = new JTextField();
                    PriorityTextFields[i].setBounds(320, (i == 0) ? 85 : 80 + (35 * i), 75, 25);
                    PriorityTextFields[i].setText(null);
                    PriorityTextFields[i].setVisible(true);
                    ProcessPanel.add(PriorityTextFields[i]);
                }
                ProcessPanel.repaint();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Quantity selected is invalid!");
        }
    }//GEN-LAST:event_AmountComboBoxActionPerformed

    private void AlgorithmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgorithmButtonActionPerformed
        int algorithm = Integer.parseInt(AlgorithmComboBox.getSelectedItem().toString());

    }//GEN-LAST:event_AlgorithmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Process().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlgorithmButton;
    private javax.swing.JComboBox AlgorithmComboBox;
    private javax.swing.JLabel AlgorithmLabel;
    private javax.swing.JComboBox AmountComboBox;
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JLabel ArrivalLabel;
    private javax.swing.JLabel CPUBurstLabel;
    private javax.swing.JLabel PriorityLabel;
    private javax.swing.JLabel ProcessIdLabel;
    private javax.swing.JPanel ProcessPanel;
    // End of variables declaration//GEN-END:variables
}
